name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install and Build
      run: yarn && yarn build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.actions }}
        BRANCH: gh-pages
        FOLDER: dist

    # - name: Deploy
    #   uses: easingthemes/ssh-deploy@v2.0.7
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
    #     ARGS: "-avz --delete"
    #     SOURCE: "dist/"
    #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #     TARGET: ${{ secrets.TARGET }}

    - name: Deploy to Server # 部署到云服务器，使用easingthemes/ssh-deploy@v2.1.1，通过ssh的方式连接
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}  # 私钥，公钥拷贝到服务器在/root/.ssh/authorized_keys中中

            ARGS: ${{ secrets.ARGS }} # 对于任何初始/必需的rsync标志，默认-avzr --delete，如果目录下有其他不可删除文件或文件夹可以用--exclude忽略，如--exclude /uploads/   
            SOURCE: "dist/" # 源目录
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # 服务器地址
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }} # ssh连接端口号
            REMOTE_USER: root # 连接用户名
            TARGET: ${{ secrets.REMOTE_TARGET }} # 目标部署目录